# image: gitlab.lnu.se:5050/1dv025/pipelines/docker-images

image: node:20

# Gitlab has built-in templates that we can use for different checks. 
# This one is documented at https://docs.gitlab.com/ee/user/application_security/secret_detection/
# and will automatically run during the "test"-stage
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test
  - review
  - production

variables:
  NODE_ENV: development
  # TESTCAFE_BROWSER_INIT_TIMEOUT: 600000

cache:
  paths:
    - node_modules/
    - .npm/

before_script:
  - echo "Running before_script"
  - rm -rf node_modules/
  - rm -f package-lock.json
  - npm install
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H cscloud7-95.lnu.se >> ~/.ssh/known_hosts
  - echo "$PRIVATE_KEY" > ./private.pem
  - echo "$PUBLIC_KEY" > ./public.pem

build_system:
  stage: build
  script:
    - echo "Building..."
    - rm -rf node_modules/
    - rm -f package-lock.json
    - npm install

Code Linting:
  stage: test
  
  script:
    - echo "Code Linting...."
    - npm run lint


unit_tests:
  stage: test
  script:
    - echo "Running Unit tests..."
    - npm run test

deploy_to_testenv:
  stage: review
  script:
    - echo "Deploying to review server"
    - echo "Building the application..."
    - rm -rf node_modules/
    - rm -f package-lock.json
    - npm install
    - npm run build
    - echo "Copying files to the server"
    - scp -r ./dist/* ubuntu@cscloud7-95.lnu.se:/var/www/petsee/dist
    - echo "Running deployment script on the server..."
    - ssh ubuntu@cscloud7-95.lnu.se 'bash /var/www/petsee/scripts/deploy.sh'

  #rules:
    # We want to production as a manual step.
    #- when: manual

Deploy to production:
  stage: production
  script:
    - echo "Deploying to production server"
    - echo "Building the application..."
    - npm run build
    - scp -r ./dist/* ubuntu@cscloud7-95.lnu.se:/var/www/petsee/dist
    - echo "Running deployment script on the server..."
    - ssh ubuntu@cscloud7-95.lnu.se 'bash /var/www/petsee/scripts/deploy.sh'
  #rules:
  #  - when: manual    

