# Using latest node version
image: gitlab.lnu.se:5050/1dv025/pipelines/docker-images

# Gitlab has built-in templates that we can use for different checks. 
# This one is documented at https://docs.gitlab.com/ee/user/application_security/secret_detection/
# and will automatically run during the "test"-stage
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test
  - review
  - production

variables:
  NODE_ENV: development

cache:
  paths:
    - node_modules/
    - .npm/

before_script:
  - echo "Running before_script"
  - rm -rf node_modules/
  - rm -f package-lock.json
  - npm install

Build system:
  stage: build
  
  script:
    - echo "Building..."
    

Code Linting:
  stage: test
  
  script:
    - echo "Code Linting...."
    

Document Linting:
  stage: test
  
  script:
    - echo "Document Linting...."
    

Unit tests:
  stage: test
  
  script:
    - echo "Running Unit tests..."
    - npm run test

Other automatic tests:
  stage: test
  
  script:
    - echo "Running Other Tests..."

Deploy to testenv:
  stage: review
  
  script:
    - echo "Deploying to review server"

Deploy to production:
  stage: production
  
  script:
    - echo "Deploying to production server"
  
  rules:
    # We want to production as a manual step.
    - when: manual 
